import React, { useState, useEffect, useMemo } from 'react'
import { motion } from 'framer-motion'
import { jsPDF } from 'jspdf'
import sheetsService from '../services/sheets'
import styles from './Analytics.module.css'

const SEGMENT_LABELS = {
  'house_to_airport': 'House to Terminal',
  'terminal_to_parking': 'Terminal to Parking/Rental',
  'parking_to_security': 'Parking/Rental to Curb',
  'security_to_gate': 'Curb to Gate',
}

const SEGMENT_ORDER = ['house_to_airport', 'terminal_to_parking', 'parking_to_security', 'security_to_gate']

export default function Analytics() {
  const [loading, setLoading] = useState(true)
  const [data, setData] = useState({ trips: [], segments: [], flights: [] })
  const [activeTab, setActiveTab] = useState('time')
  const [showExportMenu, setShowExportMenu] = useState(false)

  useEffect(() => {
    loadData()
  }, [])

  async function loadData() {
    try {
      setLoading(true)
      const [trips, segments, flights] = await Promise.all([
        sheetsService.getTrips().catch(() => []),
        sheetsService.getTimeSegments().catch(() => []),
        sheetsService.getFlights().catch(() => [])
      ])
      setData({ trips, segments, flights })
    } finally {
      setLoading(false)
    }
  }

  const tripTimeStats = useMemo(() => {
    const calcStats = (trips) => {
      const times = trips.map(t => parseFloat(t.total_time)).filter(t => !isNaN(t))
      if (times.length === 0) return null
      const avg = times.reduce((a, b) => a + b, 0) / times.length
      const sorted = [...times].sort((a, b) => a - b)
      return { avg, min: sorted[0], max: sorted[sorted.length - 1], count: times.length }
    }
    const mciTrips = data.trips.filter(t => t.direction === 'MCI')
    const pdxTrips = data.trips.filter(t => t.direction === 'PDX')
    return {
      mci: calcStats(mciTrips),
      pdx: calcStats(pdxTrips)
    }
  }, [data.trips])

  const segmentStatsByAirport = useMemo(() => {
    const calcSegmentStats = (trips) => {
      const tripIds = new Set(trips.map(t => t.id))
      const relevantSegments = data.segments.filter(s => tripIds.has(s.trip_id))
      const byType = {}
      relevantSegments.forEach(seg => {
        const type = seg.segment_type
        if (!byType[type]) byType[type] = []
        const mins = parseFloat(seg.duration_minutes)
        if (!isNaN(mins)) byType[type].push(mins)
      })
      return Object.entries(byType).map(([type, times]) => {
        const avg = times.reduce((a, b) => a + b, 0) / times.length
        const sorted = [...times].sort((a, b) => a - b)
        return { type, avg, min: sorted[0], max: sorted[sorted.length - 1], count: times.length }
      })
    }
    const mciTrips = data.trips.filter(t => t.direction === 'MCI')
    const pdxTrips = data.trips.filter(t => t.direction === 'PDX')
    return {
      mci: calcSegmentStats(mciTrips),
      pdx: calcSegmentStats(pdxTrips)
    }
  }, [data.trips, data.segments])

  const flightStats = useMemo(() => {
    const cashFlights = data.flights.filter(f => f.cash_price)
    const cashPrices = cashFlights.map(f => parseFloat(f.cash_price)).filter(p => !isNaN(p))
    const avgCash = cashPrices.length > 0 ? cashPrices.reduce((a, b) => a + b, 0) / cashPrices.length : 0
    const sortedCash = [...cashPrices].sort((a, b) => a - b)
    return {
      totalFlights: data.flights.length,
      cashFlights: cashFlights.length,
      milesFlights: data.flights.filter(f => f.miles_used).length,
      avgCash,
      p25: sortedCash[Math.floor(sortedCash.length * 0.25)] || 0,
      p50: sortedCash[Math.floor(sortedCash.length * 0.5)] || 0
    }
  }, [data.flights])

  const generateTextReport = () => {
    const date = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
    let report = `AIRPORT TRAVEL TIME REPORT\n${date}\n${'═'.repeat(30)}\n\n`

    const addAirportSection = (code, stats, segments) => {
      if (!stats) return ''
      let section = `${code} AIRPORT\n${'-'.repeat(20)}\n`
      section += `Total Trips: ${stats.count}\n`
      section += `Average: ${stats.avg.toFixed(0)} min\n`
      section += `Fastest: ${stats.min.toFixed(0)} min\n`
      section += `Slowest: ${stats.max.toFixed(0)} min\n\n`

      if (segments.length > 0) {
        section += `Segments:\n`
        const sorted = [...segments].sort((a, b) => SEGMENT_ORDER.indexOf(a.type) - SEGMENT_ORDER.indexOf(b.type))
        sorted.forEach(seg => {
          const label = SEGMENT_LABELS[seg.type] || seg.type
          section += `  ${label}\n`
          section += `    Avg: ${seg.avg.toFixed(1)}m | Min: ${seg.min.toFixed(1)}m | Max: ${seg.max.toFixed(1)}m\n`
        })
      }
      return section + '\n'
    }

    report += addAirportSection('MCI', tripTimeStats.mci, segmentStatsByAirport.mci)
    report += addAirportSection('PDX', tripTimeStats.pdx, segmentStatsByAirport.pdx)
    report += `Generated by MCI-PDX Flight Intel`
    return report
  }

  const handleShareText = async () => {
    const report = generateTextReport()
    if (navigator.share) {
      try {
        await navigator.share({ title: 'Airport Travel Time Report', text: report })
      } catch (err) {
        if (err.name !== 'AbortError') {
          await navigator.clipboard.writeText(report)
          alert('Report copied to clipboard!')
        }
      }
    } else {
      await navigator.clipboard.writeText(report)
      alert('Report copied to clipboard!')
    }
    setShowExportMenu(false)
  }

  const handleExportPDF = () => {
    const doc = new jsPDF()
    const date = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
    const pageWidth = doc.internal.pageSize.getWidth()
    const margin = 20
    const contentWidth = pageWidth - (margin * 2)
    let y = 25

    // Title
    doc.setFontSize(22)
    doc.setFont('helvetica', 'bold')
    doc.text('Travel Time Report', pageWidth / 2, y, { align: 'center' })
    y += 10
    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(120)
    doc.text(date, pageWidth / 2, y, { align: 'center' })
    doc.setTextColor(0)
    y += 20

    const addAirportPDF = (code, stats, segments, color) => {
      if (!stats) return

      // Airport header bar
      doc.setFillColor(...color)
      doc.roundedRect(margin, y, contentWidth, 12, 2, 2, 'F')
      doc.setFontSize(13)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(255)
      doc.text(code + ' Airport', margin + 6, y + 8.5)
      doc.setTextColor(0)
      y += 18

      // Summary stats in a clean grid
      doc.setFontSize(10)
      const colWidth = contentWidth / 4
      const labels = ['Trips', 'Average', 'Fastest', 'Slowest']
      const values = [stats.count.toString(), `${stats.avg.toFixed(0)} min`, `${stats.min.toFixed(0)} min`, `${stats.max.toFixed(0)} min`]

      // Labels row
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(100)
      labels.forEach((label, i) => {
        doc.text(label, margin + (colWidth * i) + (colWidth / 2), y, { align: 'center' })
      })
      y += 6

      // Values row
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(0)
      values.forEach((val, i) => {
        doc.text(val, margin + (colWidth * i) + (colWidth / 2), y, { align: 'center' })
      })
      y += 12

      // Segments table
      if (segments.length > 0) {
        // Table header
        doc.setFillColor(248, 248, 248)
        doc.rect(margin, y, contentWidth, 9, 'F')
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(9)
        doc.setTextColor(80)
        doc.text('Segment', margin + 4, y + 6)
        doc.text('Avg', margin + 105, y + 6, { align: 'center' })
        doc.text('Min', margin + 130, y + 6, { align: 'center' })
        doc.text('Max', margin + 155, y + 6, { align: 'center' })
        y += 12

        // Table rows
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(40)
        const sorted = [...segments].sort((a, b) => SEGMENT_ORDER.indexOf(a.type) - SEGMENT_ORDER.indexOf(b.type))
        sorted.forEach((seg, i) => {
          // Alternating row background
          if (i % 2 === 0) {
            doc.setFillColor(252, 252, 252)
            doc.rect(margin, y - 5, contentWidth, 9, 'F')
          }
          const label = SEGMENT_LABELS[seg.type] || seg.type
          doc.setFontSize(9)
          doc.text(label, margin + 4, y)
          doc.text(`${seg.avg.toFixed(1)}`, margin + 105, y, { align: 'center' })
          doc.text(`${seg.min.toFixed(1)}`, margin + 130, y, { align: 'center' })
          doc.text(`${seg.max.toFixed(1)}`, margin + 155, y, { align: 'center' })
          y += 9
        })
      }
      y += 15
    }

    addAirportPDF('MCI', tripTimeStats.mci, segmentStatsByAirport.mci, [59, 130, 246])
    addAirportPDF('PDX', tripTimeStats.pdx, segmentStatsByAirport.pdx, [34, 197, 94])

    // Footer
    doc.setFontSize(8)
    doc.setTextColor(160)
    doc.text('Generated by MCI-PDX Flight Intel', pageWidth / 2, 285, { align: 'center' })

    doc.save('travel-time-report.pdf')
    setShowExportMenu(false)
  }

  if (loading) {
    return <div className={styles.container}><div className={styles.loading}>Loading analytics...</div></div>
  }

  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <h1>Analytics</h1>
        <p>Your travel patterns</p>
      </header>

      <div className={styles.tabs}>
        <button className={`${styles.tab} ${activeTab === 'time' ? styles.active : ''}`} onClick={() => setActiveTab('time')}>Time</button>
        <button className={`${styles.tab} ${activeTab === 'flights' ? styles.active : ''}`} onClick={() => setActiveTab('flights')}>Flights</button>
      </div>

      {activeTab === 'time' && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className={styles.tabContent}>
          <div className={styles.airportCards}>
            {tripTimeStats.mci && (
              <div className={`${styles.summaryCard} ${styles.mciCard}`}>
                <h3 className={styles.mciHeader}>MCI</h3>
                <div className={styles.summaryGrid}>
                  <div className={styles.summaryItem}><span className={styles.summaryValue}>{tripTimeStats.mci.avg.toFixed(0)}</span><span className={styles.summaryLabel}>Avg (min)</span></div>
                  <div className={styles.summaryItem}><span className={styles.summaryValue}>{tripTimeStats.mci.min.toFixed(0)}</span><span className={styles.summaryLabel}>Best</span></div>
                  <div className={styles.summaryItem}><span className={styles.summaryValue}>{tripTimeStats.mci.max.toFixed(0)}</span><span className={styles.summaryLabel}>Worst</span></div>
                  <div className={styles.summaryItem}><span className={styles.summaryValue}>{tripTimeStats.mci.count}</span><span className={styles.summaryLabel}>Trips</span></div>
                </div>
              </div>
            )}
            {tripTimeStats.pdx && (
              <div className={`${styles.summaryCard} ${styles.pdxCard}`}>
                <h3 className={styles.pdxHeader}>PDX</h3>
                <div className={styles.summaryGrid}>
                  <div className={styles.summaryItem}><span className={styles.summaryValue}>{tripTimeStats.pdx.avg.toFixed(0)}</span><span className={styles.summaryLabel}>Avg (min)</span></div>
                  <div className={styles.summaryItem}><span className={styles.summaryValue}>{tripTimeStats.pdx.min.toFixed(0)}</span><span className={styles.summaryLabel}>Best</span></div>
                  <div className={styles.summaryItem}><span className={styles.summaryValue}>{tripTimeStats.pdx.max.toFixed(0)}</span><span className={styles.summaryLabel}>Worst</span></div>
                  <div className={styles.summaryItem}><span className={styles.summaryValue}>{tripTimeStats.pdx.count}</span><span className={styles.summaryLabel}>Trips</span></div>
                </div>
              </div>
            )}
          </div>

          {(tripTimeStats.mci || tripTimeStats.pdx) && (
            <div className={styles.exportSection}>
              <button className={styles.exportButton} onClick={() => setShowExportMenu(!showExportMenu)}>
                Share Report
              </button>
              {showExportMenu && (
                <div className={styles.exportMenu}>
                  <button onClick={handleShareText}>Share as Text</button>
                  <button onClick={handleExportPDF}>Download PDF</button>
                </div>
              )}
            </div>
          )}

          {(!tripTimeStats.mci && !tripTimeStats.pdx) && (
            <div className={styles.empty}>No trip data yet. Start logging trips!</div>
          )}

          {(segmentStatsByAirport.mci.length > 0 || segmentStatsByAirport.pdx.length > 0) && (
            <>
              {segmentStatsByAirport.mci.length > 0 && (
                <>
                  <h3 className={`${styles.sectionTitle} ${styles.mciHeader}`}>MCI Segments</h3>
                  <div className={styles.segmentList}>
                    {segmentStatsByAirport.mci.map(stat => (
                      <div key={stat.type} className={`${styles.segmentCard} ${styles.mciSegment}`}>
                        <div className={styles.segmentHeader}>
                          <span className={styles.segmentType}>{SEGMENT_LABELS[stat.type] || stat.type.replace(/_/g, ' ')}</span>
                          <span className={styles.segmentCount}>{stat.count} samples</span>
                        </div>
                        <div className={styles.segmentStats}>
                          <div className={styles.segmentStat}><span className={styles.statValue}>{stat.avg.toFixed(1)}</span><span className={styles.statLabel}>avg</span></div>
                          <div className={styles.segmentStat}><span className={styles.statValue}>{stat.min.toFixed(1)}</span><span className={styles.statLabel}>min</span></div>
                          <div className={styles.segmentStat}><span className={styles.statValue}>{stat.max.toFixed(1)}</span><span className={styles.statLabel}>max</span></div>
                        </div>
                      </div>
                    ))}
                  </div>
                </>
              )}
              {segmentStatsByAirport.pdx.length > 0 && (
                <>
                  <h3 className={`${styles.sectionTitle} ${styles.pdxHeader}`}>PDX Segments</h3>
                  <div className={styles.segmentList}>
                    {segmentStatsByAirport.pdx.map(stat => (
                      <div key={stat.type} className={`${styles.segmentCard} ${styles.pdxSegment}`}>
                        <div className={styles.segmentHeader}>
                          <span className={styles.segmentType}>{SEGMENT_LABELS[stat.type] || stat.type.replace(/_/g, ' ')}</span>
                          <span className={styles.segmentCount}>{stat.count} samples</span>
                        </div>
                        <div className={styles.segmentStats}>
                          <div className={styles.segmentStat}><span className={styles.statValue}>{stat.avg.toFixed(1)}</span><span className={styles.statLabel}>avg</span></div>
                          <div className={styles.segmentStat}><span className={styles.statValue}>{stat.min.toFixed(1)}</span><span className={styles.statLabel}>min</span></div>
                          <div className={styles.segmentStat}><span className={styles.statValue}>{stat.max.toFixed(1)}</span><span className={styles.statLabel}>max</span></div>
                        </div>
                      </div>
                    ))}
                  </div>
                </>
              )}
            </>
          )}
        </motion.div>
      )}

      {activeTab === 'flights' && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className={styles.tabContent}>
          <div className={styles.summaryCard}>
            <h3>Flight Summary</h3>
            <div className={styles.summaryGrid}>
              <div className={styles.summaryItem}><span className={styles.summaryValue}>{flightStats.totalFlights}</span><span className={styles.summaryLabel}>Total</span></div>
              <div className={styles.summaryItem}><span className={styles.summaryValue}>{flightStats.cashFlights}</span><span className={styles.summaryLabel}>Cash</span></div>
              <div className={styles.summaryItem}><span className={styles.summaryValue}>{flightStats.milesFlights}</span><span className={styles.summaryLabel}>Miles</span></div>
            </div>
          </div>
          {flightStats.avgCash > 0 && (
            <div className={styles.priceCard}>
              <h3>Cash Price Analysis</h3>
              <div className={styles.priceGrid}>
                <div className={styles.priceItem}><span className={styles.priceLabel}>Average</span><span className={styles.priceValue}>${flightStats.avgCash.toFixed(0)}</span></div>
                <div className={styles.priceItem}><span className={styles.priceLabel}>25th %ile</span><span className={styles.priceValue}>${flightStats.p25.toFixed(0)}</span></div>
              </div>
              <p className={styles.insight}>Flights under ${flightStats.p25.toFixed(0)} are a good deal.</p>
            </div>
          )}
          {flightStats.totalFlights === 0 && <div className={styles.empty}>No flight data yet. Start adding flights!</div>}
        </motion.div>
      )}
    </div>
  )
}
